### PR TITLE
policies: widen allowed filepaths

### PR DESCRIPTION
**Pull request by supakeen**
Allow writing files into `/home`, `/srv`, `/opt`. Allow writing directories into `/srv` and `/opt` but not `/home`.

### CODE REVIEW

**Review by ondrejbudai — CHANGES_REQUESTED** [review]
I think we should apply this only to non-ostree artifacts for the starters. With ostree, it gets weird, because IIRC `/var` is problematic in commits. Also, we should probably discuss this with the edge folks before committing to any changes there.

**Comment by supakeen** [comment]
@ondrejbudai @achilleas-k do we want the ostree-specific allowed paths to be what we had or do we have a widened set for those as well?

**Comment by achilleas-k** [comment]
Let's keep the old ones for now and widen then in a separate PR

**Comment by supakeen** [comment]
Should we allow `/usr/local/s?bin` for the ostree policies? They were recently added for non-ostree.

**Review by ondrejbudai — DISMISSED** [review]
Splendid! :heart:

**Comment by achilleas-k** [comment]
Merge conflicts :/
Good to merge once that's resolved though :+1:

**Comment by supakeen** [comment]
@achilleas-k Rebased.

**Comment by ezr-ondrej** [comment]
Have we reverted https://github.com/osbuild/images/pull/528 by this PR?
I think the goal there was to allow `/usr/local/sbin` for firstboot scripts, was it an intention here to disable it again?

**Comment by lzap** [comment]
Yeah: https://github.com/osbuild/images/pull/587

**Pull request merged**
