### PR TITLE
Fedora update deps

### PR DESCRIPTION
**Pull request by nullr0ute**
This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

This updates the IoT package set to what we currently ship in upstream Fedora IoT to align them. It ensures we have things like the split out WiFi firmware, the new podman 4 networking stack and other things that have changed since we first landed the ostree support in osbuild.

A second patch also updates the general Fedora firmware to the new naming. This can be split out to a different PR but it is related.

### CODE REVIEW

**Comment by achilleas-k** [comment]
Thanks for the update.  And for ordering alphabetically (we try to keep these lists ordered but some of them haven't been touched in a while and weren't ordered to begin with).
I'm seeing package selection failures:
```
missing packages: iwlwifi-dvm-firmware, iwlwifi-mvm-firmware
```

I assume this is a recent change that we haven't pulled into our test repos yet?

I'll have to update the test generators to use new snapshots.

**Comment by nullr0ute** [comment]
> ```
> missing packages: iwlwifi-dvm-firmware, iwlwifi-mvm-firmware
> ```
> 
> I assume this is a recent change that we haven't pulled into our test repos yet?

The iwlwifi changes landed beginning of July (2nd I think) with linux-firmware-20230625-151, it's been stable soon after for F-38, and ~3 weeks for F-37. The other WiFi changes have been there 3-4 months.

**Comment by achilleas-k** [comment]
Made a separate PR to update the repo snapshots for the tests.

**Comment by achilleas-k** [comment]
Pushed an extra commit that makes `fdo-client` conditional on distro version since it's not available in F37 and we still have support for it.

**Review by achilleas-k — APPROVED** [review]

**Review by achilleas-k — DISMISSED** [review]

**Review by achilleas-k — DISMISSED** [review]

**Comment by achilleas-k** [comment]
@nullr0ute `rng-tools` was removed from the `iotCommitPackageSet`.  Was that accidental?

**Comment by nullr0ute** [comment]
> @nullr0ute `rng-tools` was removed from the `iotCommitPackageSet`. Was that accidental?

Nope, intended. We've not included it upstream for some time, with changes to how upstream kernel deals with RNG it provided little to no value mixing in extra.

**Comment by achilleas-k** [comment]
> > @nullr0ute `rng-tools` was removed from the `iotCommitPackageSet`. Was that accidental?
> 
> Nope, intended. We've not included it upstream for some time, with changes to how upstream kernel deals with RNG it provided little to no value mixing in extra.

Thanks.  Pushed one more commit to remove the rngd.service from the default services then.

**Review by achilleas-k — DISMISSED** [review]

**Review by achilleas-k — APPROVED** [review]

**Pull request merged**
