### PR TITLE
repo: Fedora 41 repositories

### PR DESCRIPTION
**Pull request by supakeen**
Fedora 41 repositories

### CODE REVIEW

**Review by ondrejbudai — DISMISSED** [review]
Thanks!

**Review by thozza — APPROVED** [review]
LGTM

**Comment by supakeen** [comment]
It seems there are missing packages in Fedora 41: `podman-plugins` which is required by a few image types (`iot-container`, `iot-commit`).

**Comment by supakeen** [comment]
I've dismissed the reviews on this PR until the above can be resolved.

**Comment by paulwhalen** [comment]
> It seems there are missing packages in Fedora 41: `podman-plugins` which is required by a few image types (`iot-container`, `iot-commit`) and defined in the `iot-commit` package set.
> 
> The subpackage `podman-plugins` was removed in this commit for `podman` 5.0: https://src.fedoraproject.org/rpms/podman/c/2ab1bb3d2d6b3e9df18449494a081fcbe8044d4c?branch=rawhide
> 
> I'll tag @paulwhalen and @nullr0ute on this, we can disable `podman-plugins` conditionally for Fedora > 40 though it seems 5.0 is also in 40 itself?

Right, podman-5.0 is included in F40, so the change should be made there as well. 

We also had to drop `passwd` as its provided by `shadow-utils` in F40+

**Comment by supakeen** [comment]
> > It seems there are missing packages in Fedora 41: `podman-plugins` which is required by a few image types (`iot-container`, `iot-commit`) and defined in the `iot-commit` package set.
> > The subpackage `podman-plugins` was removed in this commit for `podman` 5.0: https://src.fedoraproject.org/rpms/podman/c/2ab1bb3d2d6b3e9df18449494a081fcbe8044d4c?branch=rawhide
> > I'll tag @paulwhalen and @nullr0ute on this, we can disable `podman-plugins` conditionally for Fedora > 40 though it seems 5.0 is also in 40 itself?
> 
> Right, podman-5.0 is included in F40, so the change should be made there as well.
> 
> We also had to drop `passwd` as its provided by `shadow-utils` in F40+

Right, do you or @nullr0ute want to write a PR to drop those packages from the package sets for Fedora >= 40 or shall I do it for you?

**Comment by paulwhalen** [comment]
> > > It seems there are missing packages in Fedora 41: `podman-plugins` which is required by a few image types (`iot-container`, `iot-commit`) and defined in the `iot-commit` package set.
> > > The subpackage `podman-plugins` was removed in this commit for `podman` 5.0: https://src.fedoraproject.org/rpms/podman/c/2ab1bb3d2d6b3e9df18449494a081fcbe8044d4c?branch=rawhide
> > > I'll tag @paulwhalen and @nullr0ute on this, we can disable `podman-plugins` conditionally for Fedora > 40 though it seems 5.0 is also in 40 itself?
> > 
> > 
> > Right, podman-5.0 is included in F40, so the change should be made there as well.
> > We also had to drop `passwd` as its provided by `shadow-utils` in F40+
> 
> Right, do you or @nullr0ute want to write a PR to drop those packages from the package sets for Fedora >= 40 or shall I do it for you?

I can do the PR, sorry the delayed response.

**Comment by supakeen** [comment]
Thank you @paulwhalen.

**Comment by supakeen** [comment]
Rebased now that #480 has landed in main which should turn this PR green.

**Comment by supakeen** [comment]
@ondrejbudai @achilleas-k it seems the CI for the `iot-bootable-container` is an actual failure but I haven't been able to figure out why yet. Does either of you have an idea?

**Review by achilleas-k — APPROVED** [review]

**Comment by achilleas-k** [comment]
https://issues.redhat.com/browse/RHEL-29559 is happening in F41 now too.

**Comment by achilleas-k** [comment]
If we want to bring F41 repos and builds and avoid the issue with rpm-ostree we could temporarily disable the ostree-based image types in F41 only.

**Pull request closed without merging**
