### PR TITLE
github: fix bib update workflow: check out sources first

### PR DESCRIPTION
**Pull request by achilleas-k**
Kinda necessary

### CODE REVIEW

**Review by ondrejbudai — APPROVED** [review]
looks kinda good

**Comment by achilleas-k** [comment]
Testing here https://github.com/osbuild/images/actions/workflows/update-bootc-image-builder.yml

**Review by ondrejbudai — DISMISSED** [review]

**Comment by achilleas-k** [comment]
Does the org-wide `SCHUTZBOT_GITHUB_ACCESS_TOKEN` have push access?  I see `rpmrepo` uses a repository-specific token variable instead of that to push the snapshot update PRs, so maybe we need a new one here too?

**Comment by achilleas-k** [comment]
IT WORKS:
- Action: https://github.com/osbuild/images/actions/runs/8350875915/job/22858182550
- PR: https://github.com/osbuild/images/pull/532

**Review by ondrejbudai — APPROVED** [review]

**Pull request merged**
