### PR TITLE
Run CI build on Fedora 40 runners

### PR DESCRIPTION
**Pull request by achilleas-k**
Update the GitLab CI configurations (static and autogenerated) to use Fedora 40 runners.
Also, pull in a new version of osbuild to test the new optional metadata selection for depsolving [1] and to make sure everything is rebuilt.

[1] https://github.com/osbuild/osbuild/pull/1775

### CODE REVIEW

**Review by thozza — APPROVED** [review]
LGTM.

Seeing so many changed lines in `.gitlab-ci.yml` made me wondering it we should simply define the fedora runners as variables at the top of the file and use those everywhere instead.

**Comment by achilleas-k** [comment]
> LGTM.
> 
> Seeing so many changed lines in `.gitlab-ci.yml` made me wondering it we should simply define the fedora runners as variables at the top of the file and use those everywhere instead.

yeah, I think you might be right.
Though that file is generated from `./test/scripts/generate-gitlab-ci` (and checked in tests).  But the other generators (the dynamic ones) also need to be in sync so we could probably put it in a config somewhere anyway.

**Comment by achilleas-k** [comment]
Btw, found a bug: https://github.com/osbuild/osbuild/pull/1795

**Review by bcl — DISMISSED** [review]
Looks good

**Comment by thozza** [comment]
```
Traceback (most recent call last):
  File "/usr/libexec/osbuild-depsolve-dnf", line 488, in <module>
    main()
  File "/usr/libexec/osbuild-depsolve-dnf", line 480, in main
    result, err = solve(request, cachedir)
  File "/usr/libexec/osbuild-depsolve-dnf", line 371, in solve
    solver = Solver(request, persistdir, cache_dir)
  File "/usr/libexec/osbuild-depsolve-dnf", line 68, in __init__
    self.base.conf.optional_metadata_types.extend(arguments.get("optional-metadata", []))
  File "/usr/lib/python3.9/site-packages/dnf/conf/config.py", line 67, in __getattr__
    option = getattr(self._config, name)
AttributeError: 'ConfigMain' object has no attribute 'optional_metadata_types'
=== NAME  TestErrorRepoInfo
    dnfjson_test.go:723: 
        	Error Trace:	/__w/images/images/pkg/dnfjson/dnfjson_test.go:723
        	Error:      	"DNF error occurred: InternalError: Failed to unmarshal dnf-json error output \"\": unexpected end of JSON input" does not contain "https://0.0.0.0/baseos/mirrors"
        	Test:       	TestErrorRepoInfo
--- FAIL: TestErrorRepoInfo (0.60s)
```

**Review by thozza — APPROVED** [review]
:+1:

**Comment by achilleas-k** [comment]
`podman run` is failing on the runners (when trying to start ostree containers).  Something to look into next week.
I think our F40 runners are a bit old though (since before F40 GA), so might just try updating them first.

**Comment by achilleas-k** [comment]
Converting to DRAFT until the F40 runners get updated.

**Comment by achilleas-k** [comment]
Got new Fedora 40 runners thanks to @croissanne <3
Let's see if things get weird again.

**Comment by achilleas-k** [comment]
Ok the weirdness hasn't gone away.  I'm still getting permission errors when trying to run ostree containers:
```
📦 Starting container registry.gitlab.com/redhat/services/products/image-builder/ci/images/centos_9-x86_64-edge_container-empty:build-a8001dcacb938a15a1623c3cf1bde9ffe5abe13060ad246bf19b718064623db1 42000
❌ Command failed: ['podman', 'run', '-d', '--rm', '-p42000:8080', 'registry.gitlab.com/redhat/services/products/image-builder/ci/images/centos_9-x86_64-edge_container-empty:build-a8001dcacb938a15a1623c3cf1bde9ffe5abe13060ad246bf19b718064623db1']
Trying to pull registry.gitlab.com/redhat/services/products/image-builder/ci/images/centos_9-x86_64-edge_container-empty:build-a8001dcacb938a15a1623c3cf1bde9ffe5abe13060ad246bf19b718064623db1...
Getting image source signatures
Copying blob sha256:0e2f47f2266a843d0262757848e45968c4720183a7e99b3debc86686162c2c7a
Copying config sha256:09579bae409a9b8b084d0fbdb49b0f34aa4a294e88d950158590f2d52b91a368
Writing manifest to image destination
Error: crun: sd-bus call: Interactive authentication required.: Permission denied: OCI permission denied
```

While troubleshooting this, I decided to also do something I've been meaning to do for a while and switch to pulling ostree containers from the s3 bucket instead of putting them in the gitlab registry as well.  I'm going to clean up the gitlab registry so we don't have the same containers in multiple places.

**Comment by achilleas-k** [comment]
Looking around some older issues, it seems it might be a configuration issue with rootless podman.  I'm going to dig a bit more tomorrow but I'm not above just running it with sudo to get around this and move on.

**Comment by achilleas-k** [comment]
Alright, we're green!!

**Review by bcl — APPROVED** [review]
Looks good, test failures are the integration tests only.

**Pull request merged**
