### PR TITLE
Update Red Hat RPM GPG keys.

### PR DESCRIPTION
**Pull request by thozza**
Update the Red Hat GPG keys (release key and auxiliary key), which used SHA-1. SHA-1 is no longer valid in signatures on c10s / el10. Use the keys from RH customer portal, which use SHA-256 in their signature: https://access.redhat.com/security/team/key

Note that the auxiliary key is specific to each RHEL major version and the el8 key uses SHA-1 in its signature and can't be replaced with the aux key from el9.

Edit:
- I added RHEL-9.5 repo definitions.
- I deleted c8s repo definitions, since it is EOL.

### CODE REVIEW

**Review by achilleas-k — DISMISSED** [review]

**Comment by achilleas-k** [comment]
```
error: /tmp/gpgkey.x20kag8z: key 1 not an armored public key.
```
:/

**Comment by achilleas-k** [comment]
Seems to be running smoothly now.  Ready?

**Comment by achilleas-k** [comment]
> Seems to be running smoothly now. Ready?

I somehow missed that [RHEL 8.6 aarch64 failed](https://gitlab.com/redhat/services/products/image-builder/ci/images/-/pipelines/1322364603).

**Review by achilleas-k — APPROVED** [review]
SPLENDID.  Thanks for the cleanups too!!

**Comment by thozza** [comment]
> SPLENDID. Thanks for the cleanups too!!

Now 9.5 builds failed :sob:

**Comment by achilleas-k** [comment]
oh, stupid ec2-sap exception for RHEL 8.4 (which requires listing every other distro in the empty one).

**Comment by achilleas-k** [comment]
```diff
diff --git a/test/config-map.json b/test/config-map.json
index e78c8e538..3f7ed3a79 100644
--- a/test/config-map.json
+++ b/test/config-map.json
@@ -33,21 +33,13 @@
   },
   "./configs/ec2-sap-empty.json": {
     "distros": [
-      "centos-8",
-      "centos-9",
-      "fedora-39",
-      "fedora-40",
       "rhel-8.10",
       "rhel-8.5",
       "rhel-8.6",
       "rhel-8.7",
       "rhel-8.8",
       "rhel-8.9",
-      "rhel-9.0",
-      "rhel-9.1",
-      "rhel-9.2",
-      "rhel-9.3",
-      "rhel-9.4"
+      "rhel-9.*",
     ],
     "image-types": [
       "ec2-sap"
```

that'll probably fix it (and make the config more accurate)

**Comment by achilleas-k** [comment]
```
error: /tmp/gpgkey.fpnmi_os: key 1 not an armored public key.
Traceback (most recent call last):
  File "/run/osbuild/bin/org.osbuild.rpm", line 251, in <module>
    r = main(args["tree"], args["inputs"], args["options"])
  File "/run/osbuild/bin/org.osbuild.rpm", line 155, in main
    ], check=True)
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['rpmkeys', '--root', '/run/osbuild/tree', '--import', '/tmp/gpgkey.fpnmi_os']' returned non-zero exit status 1.
```
on RHEL 8.6 aarch64 ec2 and azure rhui :/

**Review by achilleas-k — APPROVED** [review]
:tada:

**Pull request merged**
