### PR TITLE
Replace s3cmd with awscli2 in test scripts

### PR DESCRIPTION
**Pull request by achilleas-k**
Quick tests showed that the sync operation is much faster with awscli2 than with s3cmd.

### CODE REVIEW

**Review by kingsleyzissou — APPROVED** [review]
Neat! How much of an improvement is it?

**Comment by achilleas-k** [comment]
> Neat! How much of an improvement is it?

The individual distro/arch `generate-build-config` jobs aren't affected at all it seems.
For example Fedora 39 x86_64:
- [before](https://gitlab.com/redhat/services/products/image-builder/ci/images/-/jobs/5950455119)
- [after](https://gitlab.com/redhat/services/products/image-builder/ci/images/-/jobs/5949677288)

It's a bit hard to say the generator cases because most of the time is spent setting up the runner and generating the manifests.
But the job that downloads all the image infos to check the coverage at the end of the pipeline (`check-build-coverage`) seems to have been impacted the most:
- [before](https://gitlab.com/redhat/services/products/image-builder/ci/images/-/jobs/5950419874)
- [after](https://gitlab.com/redhat/services/products/image-builder/ci/images/-/jobs/5949636271)

**Comment by achilleas-k** [comment]
Clicked the rebase button because the statuses on the GitHub UI seemed stuck on yellow.

**Comment by achilleas-k** [comment]
I'll have to amend https://github.com/osbuild/images/commit/b18de10038f2a37ac688305a3dbeedf9ec07c6ec because it exceeds the log limit for the check-build-coverage job and that's a useful one to have.

**Comment by kingsleyzissou** [comment]
> > Neat! How much of an improvement is it?
> 
> 
> 
> The individual distro/arch `generate-build-config` jobs aren't affected at all it seems.
> 
> For example Fedora 39 x86_64:
> 
> - [before](https://gitlab.com/redhat/services/products/image-builder/ci/images/-/jobs/5950455119)
> 
> - [after](https://gitlab.com/redhat/services/products/image-builder/ci/images/-/jobs/5949677288)
> 
> 
> 
> It's a bit hard to say the generator cases because most of the time is spent setting up the runner and generating the manifests.
> 
> But the job that downloads all the image infos to check the coverage at the end of the pipeline (`check-build-coverage`) seems to have been impacted the most:
> 
> - [before](https://gitlab.com/redhat/services/products/image-builder/ci/images/-/jobs/5950419874)
> 
> - [after](https://gitlab.com/redhat/services/products/image-builder/ci/images/-/jobs/5949636271)

Woah the check build coverage ones had an enormous improvement!

**Review by kingsleyzissou — APPROVED** [review]

**Review by supakeen — APPROVED** [review]

**Pull request merged**
